version: '3'

services:
  app:
    image: thiagosvalentim/eideasy-test:latest
    ports:
      - "80:80"
    container_name: app
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
